### ISSUE TITLE
Settings page is not working

### ISSUE THREAD

**Issue by waj** [instedd/pollit#10]
Found in v9ec384915701 (Prod)

After clicking the Settings tab, "Page not found" (404) is thrown

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/pollit/issue/10
- Originally Reported By: Mauricio Müller
- Originally Created At: 2014-04-23 13:47:09+00:00

**Comment by spalladino** [comment]
Working correctly in version `560fb1a7376673585fc029f81d642a7f2f6cd2fe`
