### ISSUE TITLE
Default Welcome Message should not be "Yes"

### ISSUE THREAD

**Issue by waj** [instedd/pollit#11]
Nice to have something like "Welcome to the poll"

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/pollit/issue/11
- Originally Reported By: Mauricio Müller
- Originally Created At: 2014-04-23 13:49:32+00:00

**Comment by pmallol** [comment]
Ok in version 6b54911ab6e2e85cddf17ded92410ad6b4bb3ee0
