### ISSUE TITLE
Incomplete Polls should be pushed to the spreadsheet

### ISSUE THREAD

**Issue by waj** [instedd/pollit#12]
When the Poll has some recurrence for each iteration the Poll is pushed to the spreadsheet only if the Poll has been completed.

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/pollit/issue/12
- Originally Reported By: Mauricio Müller
- Originally Created At: 2014-04-25 15:25:50+00:00

**Comment by spalladino** [comment]
Poll answers for the current occurrence are pushed when the user finishes answering the current occurrence.
