### ISSUE TITLE
Expose answer_received as an event to Hub

### ISSUE THREAD

**Issue by spalladino** [instedd/pollit#19]
Whenever a new answer is received in Pollit, push a notification to hub with:

* Poll (title and ID)
* Question (title and ID)
* Respondent (phone)
* Occurrence (datetime, for recurrent polls)
* Answered at (datetime)
* Answer (text)

**Comment by mmuller** [comment]
The properties are displayed when creating a new Hub Task.
New answers are not received as events by the Hub.
I tried to insert the new answers in a google spreadsheet but answer properties were not stored in the spreadsheet.

Pollit Version: 560fb1a7376673585fc029f81d642a7f2f6cd2fe
Hub Version: 1a700c0

To reproduce it:
Given a Poll 'Foo' with a enabled channel
Go to the Hub
Add a new Task
Choose 'New Answer' from 'Poll Foo' as Event
Choose a GoogleSpreadsheet as Action
Add a Field 'Answer'
Drag the pill 'Response' into the new Field 'Answer'
Save the Task
Start the Poll 'Foo' (Pollit)
Answer the Poll questions
Open the GoogleSpreadsheet

Obtained: A new column was added ('Answer'). This column is empty.
Expected: The column 'Answer' should include the new answer



![screen shot 2015-03-05 at 3 13 14 pm](https://cloud.githubusercontent.com/assets/518152/6511231/2db12da0-c34a-11e4-86c9-aface2fa2224.png)

**Comment by spalladino** [comment]
The issue was an error in the `hub.yml` config file in staging

**Comment by mmuller** [comment]
Ok in version 6b54911ab6e2e85cddf17ded92410ad6b4bb3ee0
