### ISSUE TITLE
Expose entities via API to Hub

### ISSUE THREAD

**Issue by spalladino** [instedd/pollit#20]
Expose the following entity sets to Hub:

* Polls
  * Questions
  * Respondents
  * Answers (queryable by occurrence, question and respondent)

**Comment by nditada** [comment]
Not sure what the use of having the questions as an entityset would be. What are the use cases you are imagining?

**Comment by pmallol** [comment]
Ok in version 6b54911ab6e2e85cddf17ded92410ad6b4bb3ee0
