### ISSUE TITLE
Can't delete channel

### ISSUE THREAD

**Issue by waj** [instedd/pollit#3]
When I try to delete my poll's channel I get "Invalid action. You have performed an invalid action within the site."

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/pollit/issue/3
- Originally Reported By: Martin  Verzilli
- Originally Created At: 2012-07-17 18:28:22+00:00

**Comment by pmallol** [comment]
Ok in version 6b54911ab6e2e85cddf17ded92410ad6b4bb3ee0
