### ISSUE TITLE
Design surveys within Pollit

### ISSUE THREAD

**Issue by spalladino** [instedd/pollit#30]
Add a survey designer in Pollit, in order to create a survey in-app instead of importing one from Google Forms. Keep support the same question kinds.

**Comment by spalladino** [comment]
Scenarios and considerations:
- Once a poll is created, its kind (manual or imported from google forms) cannot be changed
- Before a poll is started, all its settings (except for its kind) can be changed
- After a poll is started, only its title and description can be changed

**Comment by mmuller** [comment]
Ok in v2.0
