### ISSUE TITLE
Add validations to surveys designed within Pollit

### ISSUE THREAD

**Issue by spalladino** [instedd/pollit#31]
See #30

**Comment by spalladino** [comment]
- [ ] Required for all questions
- [ ] Text min/max length
- [ ] Text contains/not contains
- [ ] Number gt, lt, between

**Comment by spalladino** [comment]
If the validation fails, Pollit sends the user a message indicating that the answer was not understood, with further info regarding the reason that the validation failed.

**Comment by mmuller** [comment]
Ok in v2.0
