### ISSUE TITLE
Add branching to surveys designed within Pollit

### ISSUE THREAD

**Issue by spalladino** [instedd/pollit#32]
See #30

**Comment by spalladino** [comment]
Consider adding _pages_ to surveys if necessary

**Comment by spalladino** [comment]
Both surveymonkey and google forms implement the following for branching:

- Support multiple pages
- On a select-one question, support "go to page based on answer", including an option for "end survey"
- On each page, support "at the end of this page, go to..."

**Comment by spalladino** [comment]
Another option is to replace the previous comment's "goto page based on answer" and "at the end of this page goto page" options, by "goto __question__ based on answer" and "at the end of this __question__ goto __question__"

**Comment by spalladino** [comment]
Implemented:
- *Select one* questions: the user can choose which is the next question individually for each option
- Other types: the user can choose which is the next question

In all cases, only subsequent questions can be chosen (ie no going back). Also, the option to "end poll" is always available.

**Comment by mmuller** [comment]
Ok in v2.0
