### ISSUE TITLE
Show delivery status of last message for each respondent

### ISSUE THREAD

**Issue by asterite** [instedd/pollit#45]
Show whether the last message has been successfully delivered to each respondent, or if it has failed, and provide an option to retry. Requires implementing sending confirmation in LGW.

**Comment by asterite** [comment]
- [ ] Local gateway notifies nuntium of successful sending (maybe nuntium needs to change)
- [ ] Show in pollit UI the status of each respondent

**Comment by asterite** [comment]
It seems when a respondent replies, the answer goes to nuntium, nuntium does a POST and pollit returns the response answer, so we don't know what's the GUID for that newly generated AO message. We need to change it so that the message is enqueued in pollit and later sent, so we can track it.

**Comment by asterite** [comment]
The "confirmed" status is now propagated from the local gateway to Nuntium, and from there to Pollit.

@nditada Do we also need to add this functionality to the desktop local gateway?

**Comment by nditada** [comment]
no, just the LGW is perfect, thanks!

**Comment by mmuller** [comment]
Now, in Pollit-stg 2.3-pre1 the values ```Received by channel``` and ```Received by respondent``` are not shown as ```Status``` when the Respondent receives the Answers.
```Not sent``` and ```Sent to channel``` are displayed in the ```Status``` column and they are updated properly.

![screen shot 2016-04-15 at 1 56 14 pm](https://cloud.githubusercontent.com/assets/518152/14568876/e4b50fa0-0311-11e6-86cb-df7778aa8060.png)

**Comment by spalladino** [comment]
Received by channel and Received by respondent were not being displayed due to a config error in Nuntium, now fixed.

**Comment by spalladino** [comment]
Texts were renamed to _Not sent → Sent to gateway → Received by gateway → Sent to respondent_, and the Failed status was added.

**Comment by spalladino** [comment]
Also, msg status will only be displayed once the poll is started, and not during its creation and configuration phase.

**Comment by spalladino** [comment]
Fixed in `2.3-pre3`

**Comment by mmuller** [comment]
Ok in version 2.3-pre3
