### ISSUE TITLE
After clicking the "settings" tab, 404 is thrown

### ISSUE THREAD

**Issue by waj** [instedd/pollit#6]
Found in version 9ec384915701

Prerequisites: the account has a poll created
- Go to a Poll
- Click Settings

Expected: the settings page is displayed

Actual: Status Code 404

---
- Imported from BitBucket: https://bitbucket.org/instedd/pollit/issue/6
- Originally Reported By: Mauricio Müller
- Originally Created At: 2013-03-19 19:10:52+00:00

**Comment by pmallol** [comment]
Ok in version 560fb1a
