### ISSUE TITLE
Status legend is duplicated every time new respondents are added

### ISSUE THREAD

**Issue by spalladino** [instedd/pollit#60]
When editing a poll (not tested in a new poll wizard), manually adding respondents duplicates the Status legend below the table.

Found in 2.3-pre1

![screen shot 2016-04-18 at 5 12 33 pm](https://cloud.githubusercontent.com/assets/429604/14618447/fd677f00-0588-11e6-83e5-fd8094ef89e5.png)

**Comment by mmuller** [comment]
Ok in version 2.3-pre3
