### ISSUE TITLE
Export Partial Anwers

### ISSUE THREAD

**Issue by gathecageorge** [instedd/pollit#63]
While using the API to pull answers how can I do the following.

http://pollit.instedd.org/api/polls/POLL_ID/answers.json?id=LAST_ID

How can a person pass a parameter while pulling answers in JSON format instead of getting all the answers every pull. Example I pass the last ID and get any new answers from that ID.

**Comment by spalladino** [comment]
Hello @gathecageorge. The [answers endpoint](https://github.com/instedd/pollit/blob/master/app/controllers/api/answers_controller.rb#L44-L51) currently only supports filtering by the following parameters:
* `respondent_phone`
* `occurrence`
* `question_id`
* `respondent_id`

Does this help?

**Comment by gathecageorge** [comment]
@spalladino Thanks at least you have helped me find my way working around it. Thank you alot.
