### ISSUE TITLE
Using a google form that requires sign-in hangs the import button

### ISSUE THREAD

**Issue by waj** [instedd/pollit#9]
Steps: create a google form, do not uncheck "require sign-in", create new poll, copy link, click import.

result: spinning wheel forever
expected: message error reminding user to uncheck "require sign-in"

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/pollit/issue/9
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-04-21 18:40:57+00:00

**Comment by spalladino** [comment]
A message indicating _Invalid public Google Form URL_ is displayed in version `560fb1a7376673585fc029f81d642a7f2f6cd2fe`.
